"""add exercise_name to health records

Revision ID: 22cc3a2d828c
Revises: f4a181f36b11
Create Date: 2026-05-23 05:36:26.923411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cc3a2d828c'
down_revision: Union[str, Sequence[str], None] = 'f4a181f36b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_records', sa.Column('exercise_name', sa.String(length=100), nullable=True, comment='运动名称（仅EXERCISE类型使用）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_records', 'exercise_name')
    # ### end Alembic commands ###
