"""add_duration_to_health_records

Revision ID: 47480c6f3eda
Revises: d228797f27d4
Create Date: 2026-03-31 07:15:39.181329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47480c6f3eda'
down_revision: Union[str, Sequence[str], None] = 'd228797f27d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_records', sa.Column('duration', sa.Numeric(precision=10, scale=2), nullable=True, comment='补充时长(数值)，如运动分钟数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_records', 'duration')
    # ### end Alembic commands ###
