"""add_verify_code

Revision ID: 6da12094ae7c
Revises: a16888d373ce
Create Date: 2026-04-03 20:14:42.407926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6da12094ae7c'
down_revision: Union[str, Sequence[str], None] = 'a16888d373ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False, comment='接收邮箱'),
    sa.Column('code', sa.String(length=10), nullable=False, comment='6位验证码'),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False, comment='过期时间'),
    sa.Column('is_used', mysql.TINYINT(), nullable=True, comment='0:未使用, 1:已使用'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_email'), 'verification_codes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_codes_email'), table_name='verification_codes')
    op.drop_table('verification_codes')
    # ### end Alembic commands ###
