"""add_diet_details_and_macros

Revision ID: a16888d373ce
Revises: f317af71471d
Create Date: 2026-03-31 19:52:59.066437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16888d373ce'
down_revision: Union[str, Sequence[str], None] = 'f317af71471d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_records', sa.Column('meal_type', sa.String(length=20), nullable=True, comment='餐别: BREAKFAST, LUNCH, DINNER, SNACK'))
    op.add_column('health_records', sa.Column('food_name', sa.String(length=100), nullable=True, comment='食物名称'))
    op.add_column('health_records', sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=True, comment='碳水化合物(g)'))
    op.add_column('health_records', sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=True, comment='蛋白质(g)'))
    op.add_column('health_records', sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True, comment='脂肪(g)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_records', 'fat_g')
    op.drop_column('health_records', 'protein_g')
    op.drop_column('health_records', 'carbs_g')
    op.drop_column('health_records', 'food_name')
    op.drop_column('health_records', 'meal_type')
    # ### end Alembic commands ###
