"""initial_schema_v2_no_id

Revision ID: d228797f27d4
Revises: 
Create Date: 2026-03-31 04:56:33.464654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd228797f27d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_goals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('client_msg_id', sa.String(length=36), nullable=False),
    sa.Column('goal_type', sa.String(length=20), nullable=False, comment='LOSE:减脂, GAIN:增肌, MAINTAIN:维持'),
    sa.Column('target_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=False, comment='算法得出的每日推荐摄入热量(kcal)'),
    sa.Column('daily_burn_target', sa.Integer(), nullable=False, comment='算法得出的每日推荐运动消耗(kcal)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否为当前执行目标'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_msg_id')
    )
    op.create_index('idx_user_active', 'health_goals', ['user_id', 'is_active'], unique=False)
    op.create_table('health_records',
    sa.Column('client_msg_id', sa.String(length=36), nullable=False, comment='前端生成的唯一UUID，既是业务ID也是物理主键'),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='关联用户中心的主键'),
    sa.Column('record_type', sa.String(length=20), nullable=False, comment='类型: DIET(饮食), EXERCISE(运动), SLEEP(睡眠), WEIGHT(体重)'),
    sa.Column('record_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='数值：热量(kcal)、时长(小时)或体重(kg)'),
    sa.Column('unit', sa.String(length=10), nullable=False, comment='单位：如 kcal, hours, kg'),
    sa.Column('notes', sa.String(length=255), nullable=True, comment='用户附加备注'),
    sa.Column('record_date', sa.TIMESTAMP(), nullable=False, comment='实际打卡发生的业务时间'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='记录入库的审计时间'),
    sa.PrimaryKeyConstraint('client_msg_id')
    )
    op.create_index('idx_user_date_type', 'health_records', ['user_id', 'record_date', 'record_type'], unique=False)
    op.create_index(op.f('ix_health_records_user_id'), 'health_records', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('client_msg_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='哈希密码'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('gender', mysql.TINYINT(), nullable=True, comment='1:男, 2:女'),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activity_level', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('goal_type', sa.String(length=20), nullable=True, comment='目标类型'),
    sa.Column('target_kcal', sa.Numeric(precision=10, scale=2), nullable=True, comment='目标热量'),
    sa.Column('carbs_g', sa.Numeric(precision=10, scale=2), nullable=True, comment='碳水(g)'),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=2), nullable=True, comment='蛋白质(g)'),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=2), nullable=True, comment='脂肪(g)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_msg_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_health_records_user_id'), table_name='health_records')
    op.drop_index('idx_user_date_type', table_name='health_records')
    op.drop_table('health_records')
    op.drop_index('idx_user_active', table_name='health_goals')
    op.drop_table('health_goals')
    # ### end Alembic commands ###
