"""add_target_weight_and_snapshots_to_user

Revision ID: f317af71471d
Revises: 47480c6f3eda
Create Date: 2026-03-31 17:17:27.130205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f317af71471d'
down_revision: Union[str, Sequence[str], None] = '47480c6f3eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('target_weight', sa.Numeric(precision=10, scale=2), nullable=True, comment='用户设定的目标体重'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'target_weight')
    # ### end Alembic commands ###
