"""upgrade_chat_session_system

Revision ID: f4a181f36b11
Revises: 5a4c2861f396
Create Date: 2026-05-18 17:29:46.450760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f4a181f36b11'
down_revision: Union[str, Sequence[str], None] = '5a4c2861f396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话唯一ID(UUID)'),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='所属用户ID'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='会话动态标题'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='最后活跃时间'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_sessions_updated_at'), 'chat_sessions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.add_column('chat_messages', sa.Column('session_id', sa.String(length=36), nullable=False, comment='所属会话ID'))
    op.alter_column('chat_messages', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=64),
               comment='用户ID',
               existing_comment='关联用户ID',
               existing_nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=4000),
               comment='消息文本内容',
               existing_comment='聊天内容',
               existing_nullable=False)
    op.alter_column('chat_messages', 'is_user',
               existing_type=mysql.TINYINT(display_width=1),
               comment='1:用户发送, 0:AI回复',
               existing_comment='1: 用户发送, 0: AI回复',
               existing_nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='发送时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='发送时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_messages', 'is_user',
               existing_type=mysql.TINYINT(display_width=1),
               comment='1: 用户发送, 0: AI回复',
               existing_comment='1:用户发送, 0:AI回复',
               existing_nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=4000),
               comment='聊天内容',
               existing_comment='消息文本内容',
               existing_nullable=False)
    op.alter_column('chat_messages', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=64),
               comment='关联用户ID',
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_column('chat_messages', 'session_id')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_updated_at'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
